name: Data Refresh
on:
  schedule:
    - cron: "0 8 * * 1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Make run.sh executable
        run: chmod +x ./src/scripts/run.sh
      - name: Run the script
        run: cd src/scripts/ && ./run.sh
      - name: Set up Git config
        run: |
          git config --global user.email "${{ secrets.GH_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GH_USER_NAME }}"
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Data refresh update"
          git push origin main  # Push to 'main' branch
        env:
          # Use the GitHub token to authenticate the push
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
